server:
  port: 8082

logging:
  config: classpath:logback-local.xml

anouncy:
  cache:
    redis:
      version: 1
      server: redis://localhost:6379
      cluster: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

grpc:
  server:
    port: 9092
  client:
    persist-grpc-server:
      address: 'static://127.0.0.1:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  elasticsearch:
    uris: http://localhost:9200
    password: j6NqYdncJK9T6GHQ
    username: searcher

springdoc:
  enable-native-support: true
