prometheus:
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - prometheus.anouncy.com

  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: custom-k8s-service-endpoints
        scrape_interval: 10s
        kubernetes_sd_configs:
          - role: service
        relabel_configs:

          # annotation 'prometheus.io/scrape' must be set to 'true'
          - action: keep
            regex: true
            source_labels: [ __meta_kubernetes_service_annotation_prometheus_io_scrape ]

          # service cannot be in kube-system or prom namespaces
          - action: drop
            regex: (kube-system|prom)
            source_labels: [ __meta_kubernetes_namespace ]

          # service port name must end with word 'metrics-port'
          - action: keep
            regex: .*prometheus-port
            source_labels: [ __meta_kubernetes_service_port_name ]

          # allow override of http scheme
          - action: replace
            regex: (https?)
            source_labels: [ __meta_kubernetes_service_annotation_prometheus_io_scheme ]
            target_label: __scheme__

          # allow override of default /metrics path
          - action: replace
            regex: (.+)
            source_labels: [ __meta_kubernetes_service_annotation_prometheus_io_path ]
            target_label: __metrics_path__

          # allow override of default port
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels: [ __address__, __meta_kubernetes_service_annotation_prometheus_io_port ]
            target_label: __address__
          - { action: labelmap, regex: __meta_kubernetes_service_label_(.+) }
          - action: replace
            source_labels: [ __meta_kubernetes_namespace ]
            target_label: kubernetes_namespace
          - action: replace
            source_labels: [ __meta_kubernetes_service_name ]
            target_label: kubernetes_name

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - grafana.anouncy.com

  persistence:
    enabled: true
    size: 10Gi
  initChownData:
    enabled: false
