server:
  port: 8085

logging:
  config: classpath:logback-local.xml

anouncy:
  location:
    google:
      key: fromENV
spring:
  sql:
    init:
      mode: EMBEDDED
  application:
    name: localhost-test
  data:
    mongodb:
      host: localhost
      port: 27017
      username: ${ANOUNCY_MONGODB_USERNAME}
      password: ${ANOUNCY_MONGODB_PASSWORD}
      authentication-database: admin
      database: twitch-observer

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  task:
    execution:
      thread-name-prefix: location-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: location-scheduling-
      pool:
        size: 2
grpc:
  client:
    persist-grpc-server:
      address: 'static://127.0.0.1:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

springdoc:
  grouping:
    enable: true
    refreshTimeoutMs: 4000
    baseModule:
      description: "Location Service"
      apiUrl: http://127.0.0.1:8085/v3/api-docs.yaml
      configUrl: http://127.0.0.1:8085/v3/api-docs.yaml
    modules:
      module1:
        description: "User Service"
        apiUrl: http://127.0.0.1:8080/v3/api-docs.yaml
        configUrl: http://127.0.0.1:8080/v3/api-docs.yaml
      module2:
        description: "Announce Service"
        apiUrl: http://127.0.0.1:8081/v3/api-docs.yaml
        configUrl: http://127.0.0.1:8081/v3/api-docs.yaml
      module3:
        description: "Vote Service"
        apiUrl: http://127.0.0.1:8082/v3/api-docs.yaml
        configUrl: http://127.0.0.1:8082/v3/api-docs.yaml
      module4:
        description: "Announce Listing Service"
        apiUrl: http://127.0.0.1:8083/v3/api-docs.yaml
        configUrl: http://127.0.0.1:8083/v3/api-docs.yaml
      module5:
        description: "Region Service"
        apiUrl: http://127.0.0.1:8084/v3/api-docs.yaml
        configUrl: http://127.0.0.1:8084/v3/api-docs.yaml
      module6:
        description: "Persist Service"
        apiUrl: http://127.0.0.1:8086/v3/api-docs.yaml
        configUrl: http://127.0.0.1:8086/v3/api-docs.yaml
