server:
  port: 8085

logging:
  config: classpath:logback-test.xml

anouncy:
  location:
    google:
      key: fromENV
spring:
  sql:
    init:
      mode: EMBEDDED
  application:
    name: location-test
  data:
    mongodb:
      host: mongo.persist.svc.cluster.local
      port: 27017
      username: ENV_PARAM
      password: ENV_PARAM
      authentication-database: admin
      database: twitch-observer

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  task:
    execution:
      thread-name-prefix: location-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: location-scheduling-
      pool:
        size: 2
grpc:
  client:
    persist-grpc-server:
      address: 'static://persist-service.default.svc.cluster.local:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

springdoc:
  grpc:
    enable:
      true
  swagger-ui:
    path: "/location/swagger-ui/index.html" # this is for treafik route with prefix
  grouping:
    enable: true
    refreshTimeoutMs: 4000
    baseModule:
      description: "Location Service"
      apiUrl: https://api.anouncy.com/location
      configUrl: http://location-service.default.svc.cluster.local:8085/v3/api-docs.yaml
    modules:
      module1:
        description: "User Service"
        apiUrl: https://api.anouncy.com/user
        configUrl: http://user-service.default.svc.cluster.local:8080/v3/api-docs.yaml
      module2:
        description: "Announce Service"
        apiUrl: https://api.anouncy.com/announce
        configUrl: http://announce-service.default.svc.cluster.local:8081/v3/api-docs.yaml
      module3:
        description: "Vote Service"
        apiUrl: https://api.anouncy.com/vote
        configUrl: http://vote-service.default.svc.cluster.local:8082/v3/api-docs.yaml
      module4:
        description: "Announce Listing Service"
        apiUrl: https://api.anouncy.com/listing
        configUrl: http://listing-service.default.svc.cluster.local:8083/v3/api-docs.yaml
      module5:
        description: "Region Service"
        apiUrl: https://api.anouncy.com/region
        configUrl: http://region-service.default.svc.cluster.local:8084/v3/api-docs.yaml
      module6:
        description: "Persist Service"
        apiUrl: https://api.anouncy.com/persist
        configUrl: http://persist-service.default.svc.cluster.local:8086/v3/api-docs.yaml
