server:
  port: 8085

anouncy:
  location:
    google:
      key: fromENV
spring:
  sql:
    init:
      mode: EMBEDDED
  application:
    name: localhost-test
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongo
      password: fromENV
      authentication-database: admin
      database: asd

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  task:
    execution:
      thread-name-prefix: location-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: location-scheduling-
      pool:
        size: 2
