anouncy:
  location:
    google:
      key: fromENV
spring:
  sql:
    init:
      mode: EMBEDDED
  application:
    name: localhost-test
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/location
    username: root
    password: fromENV
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongo
      password: fromENV
      authentication-database: admin
      database:

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        jdbc.time_zone: UTC

    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  task:
    execution:
      thread-name-prefix: location-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: location-scheduling-
      pool:
        size: 2
