apiVersion: v1
kind: Service
metadata:
  name: announce-service
  namespace: default
  {{- with .Values.announce.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - targetPort: {{ .Values.announce.deployment.port }}
      port: {{ .Values.announce.deployment.port }}
      name: announce-prometheus-port
  selector:
    app: announce
