apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: default
  {{- with .Values.location.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - targetPort: {{ .Values.location.deployment.port }}
      port: {{ .Values.location.deployment.port }}
      name: location-prometheus-port
    - targetPort: {{ .Values.location.deployment.grpcPort }}
      port: {{ .Values.location.deployment.grpcPort }}
      name: location-grpc-port
  selector:
    app: location
