apiVersion: v1
kind: Service
metadata:
  name: region-service
  namespace: default
  {{- with .Values.region.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - targetPort: {{ .Values.region.deployment.port }}
      port: {{ .Values.region.deployment.port }}
      name: region-prometheus-port
    - targetPort: {{ .Values.region.deployment.grpcPort }}
      port: {{ .Values.region.deployment.grpcPort }}
      name: region-grpc-port
  selector:
    app: region
