apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: default
  {{- with .Values.vote.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - targetPort: {{ .Values.vote.deployment.port }}
      port: {{ .Values.vote.deployment.port }}
      name: vote-prometheus-port
    - targetPort: {{ .Values.vote.deployment.grpcPort }}
      port: {{ .Values.vote.deployment.grpcPort }}
      name: vote-grpc-port
  selector:
    app: vote
