ingress:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-demo@kubernetescrd

user:
  deployment:
    image: "${ANOUNCY_DOCKER_HOST}/anouncy-user:27EB0D6B-AA94-46B5-83D8-D2EF294992EC"
    imagePullPolicy: Always
    port: 8080
    replicas: 1
    maxUnavailable: 0
    maxSurge: 2
    terminationGracePeriodSeconds: 10
    readynessLivenessInitialDelay: 10
    readynessLivenessPeriod: 5
    memoryRequest: '256Mi'
    memoryLimit: '768Mi'
    annotations:
  service:
    annotations:
  ingress:
    host: "user.anouncy.com"
