ingress:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-demo@kubernetescrd

user:
  deployment:
    image: "${user_deployment_image}"
    jvmOpts: "-Dfile.encoding=UTF-8 -Dspring.profiles.active=test -Dlog4j2.formatMsgNoLookups=true"
    imagePullPolicy: Always
    port: 8080
    replicas: 1
    maxUnavailable: 0
    maxSurge: 1
    terminationGracePeriodSeconds: 10
    readinessLivenessInitialDelay: 20
    readinessLivenessPeriod: 7
    memoryRequest: '256Mi'
    memoryLimit: '768Mi'
    annotations:
  service:
    annotations:
  ingress:
    host: "api.anouncy.com"
    prefix: "/user"

announce:
  deployment:
    image: "${announce_deployment_image}"
    jvmOpts: "-Dfile.encoding=UTF-8 -Dspring.profiles.active=test -Dlog4j2.formatMsgNoLookups=true"
    imagePullPolicy: Always
    port: 8081
    replicas: 1
    maxUnavailable: 0
    maxSurge: 1
    terminationGracePeriodSeconds: 10
    readinessLivenessInitialDelay: 20
    readinessLivenessPeriod: 7
    memoryRequest: '256Mi'
    memoryLimit: '768Mi'
    annotations:
  service:
    annotations:
  ingress:
    host: "api.anouncy.com"
    prefix: "/announce"

vote:
  deployment:
    image: "${vote_deployment_image}"
    jvmOpts: "-Dfile.encoding=UTF-8 -Dspring.profiles.active=test -Dlog4j2.formatMsgNoLookups=true"
    imagePullPolicy: Always
    port: 8082
    grpcPort: 9092
    replicas: 1
    maxUnavailable: 0
    maxSurge: 1
    terminationGracePeriodSeconds: 10
    readinessLivenessInitialDelay: 20
    readinessLivenessPeriod: 7
    memoryRequest: '256Mi'
    memoryLimit: '768Mi'
    annotations:
  service:
    annotations:
  ingress:
    host: "api.anouncy.com"
    prefix: "/vote"

listing:
  deployment:
    image: "${listing_deployment_image}"
    jvmOpts: "-Dfile.encoding=UTF-8 -Dspring.profiles.active=test -Dlog4j2.formatMsgNoLookups=true"
    imagePullPolicy: Always
    port: 8083
    replicas: 1
    maxUnavailable: 0
    maxSurge: 1
    terminationGracePeriodSeconds: 10
    readinessLivenessInitialDelay: 20
    readinessLivenessPeriod: 7
    memoryRequest: '256Mi'
    memoryLimit: '768Mi'
    annotations:
  service:
    annotations:
  ingress:
    host: "api.anouncy.com"
    prefix: "/listing"


region:
  deployment:
    image: "${region_deployment_image}"
    jvmOpts: "-Dfile.encoding=UTF-8 -Dspring.profiles.active=test -Dlog4j2.formatMsgNoLookups=true "
    imagePullPolicy: Always
    port: 8084
    grpcPort: 9094
    replicas: 1
    maxUnavailable: 0
    maxSurge: 1
    terminationGracePeriodSeconds: 10
    readinessLivenessInitialDelay: 20
    readinessLivenessPeriod: 7
    memoryRequest: '256Mi'
    memoryLimit: '768Mi'
    annotations:
  service:
    annotations:
  ingress:
    host: "api.anouncy.com"
    prefix: "/region"

location:
  deployment:
    image: "${location_deployment_image}"
    jvmOpts: "-Dspring.profiles.active=test -Dspringdoc.grpc.enable=false -Dspring.data.mongodb.username=${mongodb_username} -Dspring.data.mongodb.password=${mongodb_password} -Dfile.encoding=UTF-8 -Dlog4j2.formatMsgNoLookups=true"
    imagePullPolicy: Always
    port: 8085
    grpcPort: 9095
    replicas: 1
    maxUnavailable: 0
    maxSurge: 1
    terminationGracePeriodSeconds: 10
    readinessLivenessInitialDelay: 20
    readinessLivenessPeriod: 7
    memoryRequest: '256Mi'
    memoryLimit: '768Mi'
    annotations:
  service:
    annotations:
  ingress:
    host: "api.anouncy.com"
    prefix: "/location"

persist:
  deployment:
    image: "${persist_deployment_image}"
    jvmOpts: "-Dfile.encoding=UTF-8 -Dspring.profiles.active=test -Dlog4j2.formatMsgNoLookups=true -Dspring.neo4j.authentication.password=${neo4j_password}"
    imagePullPolicy: Always
    port: 8086
    grpcPort: 9096
    replicas: 1
    maxUnavailable: 0
    maxSurge: 1
    terminationGracePeriodSeconds: 10
    readinessLivenessInitialDelay: 20
    readinessLivenessPeriod: 7
    memoryRequest: '256Mi'
    memoryLimit: '768Mi'
    annotations:
  service:
    annotations:
  ingress:
    host: "api.anouncy.com"
    prefix: "/persist"

search:
  deployment:
    image: "${search_deployment_image}"
    jvmOpts: "-Dspring.profiles.active=test -Dspring.elasticsearch.username=${elasticsearch_username} -Dspring.elasticsearch.password=${elasticsearch_password} -Dfile.encoding=UTF-8 -Dlog4j2.formatMsgNoLookups=true"
    imagePullPolicy: Always
    port: 8087
    grpcPort: 9097
    replicas: 1
    maxUnavailable: 0
    maxSurge: 1
    terminationGracePeriodSeconds: 10
    readinessLivenessInitialDelay: 20
    readinessLivenessPeriod: 7
    memoryRequest: '256Mi'
    memoryLimit: '768Mi'
    annotations:
  service:
    annotations:
  ingress:
    host: "api.anouncy.com"
    prefix: "/search"
