server:
  port: 8086

org:
  neo4j:
    driver:
      pool:
        metrics-enabled: true
      config:
        encrypted: true

  level:
    org.neo4j.ogm.drivers.bolt.request.BoltRequest: debug

grpc:
  server:
    port: 9096
  client:
    persist-grpc-server:
      address: 'static://127.0.0.1:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  neo4j:
    pool:
      metrics-enabled: true
    authentication:
      username: neo4j
      password: asd123
    uri: bolt://localhost:7687
#    authentication:
#      username: ${ANOUNCY_NEO4J_USERNAME}
#      password: ${ANOUNCY_NEO4J_PASSWORD}
#
#    uri: bolt://${ANOUNCY_TEST_SERVER_IP}:7687

