server:
  port: 8086

logging:
  config: classpath:logback-test.xml

org:
  neo4j:
    driver:
      pool:
        metrics-enabled: true
      config:
        encrypted: true

  level:
    org.springframework.data.neo4j: debug

grpc:
  server:
    port: 9096
  client:
    persist-grpc-server:
      address: 'static://persist-service.default.svc.cluster.local:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  neo4j:
    pool:
      metrics-enabled: true
    authentication:
      username: neo4j
      password: asd123
    uri: bolt://prod-neo4j-neo4j-community.persist.svc.cluster.local:7687
#    authentication:
#      username: ${ANOUNCY_NEO4J_USERNAME}
#      password: ${ANOUNCY_NEO4J_PASSWORD}
#
#    uri: bolt://${ANOUNCY_TEST_SERVER_IP}:7687

