server:
  port: 8083

logging:
  config: classpath:logback-local.xml

anouncy:
  cache:
    redis:
      version: 1
      server: redis://localhost:6379
      cluster: false

grpc:
  server:
    port: 9093
  client:
    persist-grpc-server:
      address: 'static://127.0.0.1:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    vote-grpc-server:
      address: 'static://127.0.0.1:9092'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    search-grpc-server:
      address: 'static://127.0.0.1:9097'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false

