server:
  port: 8081

logging:
  config: classpath:logback-test.xml

anouncy:
  cache:
    redis:
      version: 1
      server: redis://redis-master.persist.svc.cluster.local:6379
      cluster: false

grpc:
  server:
    port: 9091
  client:
    persist-grpc-server:
      address: 'static://persist-service.default.svc.cluster.local:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    vote-grpc-server:
      address: 'static://vote-service.default.svc.cluster.local:9092'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    region-grpc-server:
      address: 'static://region-service.default.svc.cluster.local:9094'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false


