server:
  port: 8081

anouncy:
  cache:
    redis:
      version: 1
      server: redis://localhost:6379
      cluster: false

grpc:
  server:
    port: 9091
  client:
    persist-grpc-server:
      address: 'static://127.0.0.1:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    vote-grpc-server:
      address: 'static://127.0.0.1:9092'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    region-grpc-server:
      address: 'static://127.0.0.1:9094'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  elasticsearch:
    uris: http://localhost:9200
    password: j6NqYdncJK9T6GHQ
    username: searcher

