anouncy:
  cache:
    redis:
      version: 1
      server: redis://localhost:6379
      cluster: false

org:
  neo4j:
    driver:
      pool:
        metrics-enabled: true

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  neo4j:
    pool:
      metrics-enabled: true
    authentication:
      username: neo4j
      password: fromENV
    uri: bolt://localhost:7687

