server:
  port: 8084

logging:
  config: classpath:logback-test.xml

anouncy:
  cache:
    redis:
      version: 1
      server: redis://redis-master.persist.svc.cluster.local:6379
      cluster: false

grpc:
  server:
    port: 9094
  client:
    persist-grpc-server:
      address: 'static://persist-service.default.svc.cluster.local:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
