server:
  port: 8084

logging:
  config: classpath:logback-local.xml

anouncy:
  cache:
    redis:
      version: 1
      server: redis://localhost:6379
      cluster: false

grpc:
  server:
    port: 9094
  client:
    location-grpc-server:
      address: 'static://127.0.0.1:9095'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    persist-grpc-server:
      address: 'static://127.0.0.1:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
