server:
  port: 8080

logging:
  config: classpath:logback-test.xml

grpc:
  server:
    port: 9090
  client:
    persist-grpc-server:
      address: 'static://persist-service.default.svc.cluster.local:9096'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://postgres.persist.svc.cluster.local:5432/user_management
    username: postgres_db_user
    password: 8HdN8WD746iQ
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

management:
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

anouncy:
  cache:
    redis:
      version: 1
      server: redis://redis-master.persist.svc.cluster.local:6379
      cluster: false
  jwtToken:
    secret: asdasdwqeqdaasdasdasdasdasdasdasdasdasdlmaslkdmalskdmalksdmalksmdlamksdlkadsasdasdasdasdasdasdasdasdweqweasdadqweqwe
  password:
    salt:
      user: ASDsdasd
      anonymous: asASdasdAsd
      session: asASdasdasdAsd
